services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    depends_on:
      - miniflux-db
    environment:
      - DATABASE_URL=postgres://miniflux:miniflux@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${MINIFLUX_ADMIN_USER}
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASS}
      - POLLING_FREQUENCY=30
      - SCHEDULER_FREQUENCY=1
      - CLEANUP_ARCHIVE_READ_DAYS=30
    ports:
      - "8081:8080"
    restart: unless-stopped

  miniflux-db:
    image: postgres:15
    container_name: miniflux-db
    environment:
      - POSTGRES_USER=${MINIFLUX_DB_USER}
      - POSTGRES_PASSWORD=${MINIFLUX_DB_PASS}
      - POSTGRES_DB=${MINIFLUX_DB_NAME}
    volumes:
      - ./flux/miniflux-db:/var/lib/postgresql/data
    restart: unless-stopped
